### ISSUE TITLE
Guidance for process.env

### ISSUE THREAD

**Issue by PSchicht** [OfficeDev/Office-Addin-Scripts#178]
Hi

I created a React Word AddIn and want to use something like process.env.ENVIRONMENT. Can you please provide some guidance on how to determine if the code is running locally or in production?

Thank you!
Pascal

**Comment by akrantz** [comment]
When the local dev server is run ("npm run dev-server" invokes "webpack --mode development"), process.env.NODE_ENV will be set to "development".  Otherwise, the value will be "production".

Webpack does this automatically. More info is available here:
https://webpack.js.org/guides/production/#specify-the-mode
