### ISSUE TITLE
setting for enabling loopback for edge does not get saved when called through office-addin-dev-settings

### ISSUE THREAD

**Issue by zhngx** [OfficeDev/Office-Addin-Scripts#310]
# Expected behavior

When using office-addin-dev-settings to enable loopback for Edge, expect to set it once and the settings get saved so it does not need to prompt the user for confirmation to set the loopback.

# Current behavior

The prompt for enabling loopback confirmation keeps showing up, so when using office-addin-debugging to sideload office during automation, the automation will get paused.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. call ensureLoopbackIsEnabled in code to enable the loopback
2. call npx office-addin-debugging start ...  it will prompt again for enabling the loopback

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: 1903
* Node version: 12.16.1
* Office version:
* Tool version: office-addin-debugging@3.0.27 or above

**Comment by LouMM** [comment]
Thank you, Zheng! We are looking into it.

**Comment by TCourtneyOwen** [comment]
Yup we are hitting this in our CI loops as well and it's blocking automation

**Comment by TCourtneyOwen** [comment]
I am going to investigate this today as this is critical to allow our CI pipelines to work.  I looked at the commit history and we haven't made any conspicuous changes to office-addin-dev-settings, so it's possible that recent package updates impacted things somehow, although we don't have any test failures that would indicate that

**Comment by TCourtneyOwen** [comment]
It appears that running "npx office-addin-dev-settings appcontainer EdgeWebView --loopback --yes" does not if fact set the loopback exemption. Here's what I see after I run the aforementioned command and then run "checknetisolation loopbackexempt -s":  

[1] -----------------------------------------------------------------
    Name: AppContainer NOT FOUND
    SID:  S-1-15-2-1310292540-1029022339-4008023048-2190398717-53961996-4257829345-603366646

After I run  npx office-addin-debugging start and then say yes to the prompt (which shouldn't appear because it should have been set already via "npx office-addin-dev-settings appcontainer EdgeWebView --loopback --yes"), the loopback is successfully set.  CheckNetIsolation LoopbackExempt shows the following:

[1] -----------------------------------------------------------------
    Name: microsoft.win32webviewhost_cw5n1h2txyewy
    SID:  S-1-15-2-1310292540-1029022339-4008023048-2190398717-53961996-4257829345-603366646

So, it would appear that this command is no longer working as expected:  npx office-addin-dev-settings appcontainer EdgeWebView --loopback --yes

**Comment by TCourtneyOwen** [comment]
@zhngx I am not able to get a consistent repro of this behavior.  Are you?

**Comment by TCourtneyOwen** [comment]
Interestingly, on the VMs even I run the following command to manually set the loopback exemption, the setting isn't saved: "CheckNetIsolation.exe LoopbackExempt -a -n=Microsoft.win32webviewhost_cw5n1h2txyewy"

However if I run the exact same command on my laptop, the setting is saved and I am not subsequently prompted when running office-addin-debugging

**Comment by LouMM** [comment]
@zhngx Let us know if you are still seeing this issue with the latest version of the package on the VM's. Thank you again for reporting. Let us know!
