### ISSUE TITLE
The addin is no longer available:add-in inserted during development are only available during debugging in Visual Studio

### ISSUE THREAD

**Issue by chenxizhang** [OfficeDev/Office-Addin-Scripts#347]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x ] I am running the latest version of Node and the tools
- [x ] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

# Expected behavior

I created an excel addin by "yo office", it works fine before, but I found it can't work anymore from yesterday. I don't know what happen there.

# Current behavior

I ran the command "npm start" or "yarn start" in the terminal of VS Code, it can build, and open Excel, but the add-in can't be loaded with below error

![image](https://user-images.githubusercontent.com/1996954/100824949-05140600-3492-11eb-909c-ca9712bdfb24.png)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10 2020 H2
* Node version:  14.15.1
* Office version:  latest version of Microsoft 365
* Tool version: 

## Failure Logs

Please include any relevant log snippets, screenshots or code samples here.

**Comment by awasser-omnispear** [comment]
I encountered this issue as well.  I ran `office-addin-dev-settings registered` to see which manifests are registered with Excel.   Then removed them all one at a time with `office-addin-dev-settings unregister <<manifest path>>`.
Doing this resolved that issue.

**Comment by KelBowen** [comment]
@TCourtneyOwen note that there are two customers reporting this issue.

**Comment by TCourtneyOwen** [comment]
@awasser-omnispear @chenxizhang Is the dev-server in fact started, assuming this add-in is set to localhost?

**Comment by awasser-omnispear** [comment]
It's been a bit since I've had issues with this.  I've since just wiped everything clean and started again.  My use case is fairly specific:  I've got an existing app which I'd like to integrate ReactJS, custom functions, and the new build process.  

I think I took the ReactJS Typescript base from Yo Office and applied the differences from the template from https://github.com/OfficeDev/Excel-Custom-Functions.
I don't remember exactly what I did to make it all work, but it does work now.

Couple of things I did find out while doing this:
- Run all NPM commands (including install & build) in Windows.  Not WSL, or Linux, or a Docker container.
- Don't try to update packages to current versions.
- Run the manifest validator after you make any changes to it.  Even then, make doubly sure it's valid, comparing it with the original.

Sorry I can't be any more of help.  As I said before, I've got the sideloading working now.  I hope @chenxizhang has similar luck!

**Comment by TCourtneyOwen** [comment]
Thanks for the response @awasser-omnispear I am glad to hear things are working for you and sorry to hear you were having problems.  We have heard from others who are having problems starting the dev-server and am wondering if your issue is related. One person mentioned that downgrading webpack-cli to an earlier version fixed their problem with starting the dev-server.  

-Courtney

**Comment by awasser-omnispear** [comment]
I've always been able to start the dev-server, either through `npm run start` or `npm run dev-server`.
I was not able to get to the root cause.  The biggest thing to look out for is running all the commands in a Windows PowerShell or command line; not WSL (my usual dev environment).  I believe that is where my issue stemmed from.

**Comment by millerds** [comment]
Is anyone still having trouble with this?

**Comment by igor-ribeiiro** [comment]
I will be closing this issue since there was no response to the previous callout message.
Please, feel free to reopen if the issue still exists.

**Comment by Metab0i** [comment]
it usually means that "something is wrong", but it doesn't tell you what exactly is wrong. Said "something is wrong" is contained within the manifest, so usually it's the formatting of your XML. That's my experience with it thus far anyway.

**Comment by Tom-H2oThermo** [comment]
I'm having that same error.  I'm trying to update my manifest production for submitting my app to the Partner Center/App Store.  It was working in localhost.  Then I changed one manifest line from bt:Url id="Functions.Metadata.Url" DefaultValue="https://localhost:3000/public/functions.json" to a Azure blob hosted file link.  The link works but I got that same error:
![Add-In Error](https://github.com/OfficeDev/Office-Addin-Scripts/assets/25697066/e4a4804f-54ec-4d78-8c73-dba5e8f76b99)
I then put the bt:Url line back to the way it was and ran NPM start again, and I'm getting the same error.  Now I need to figure out how to get back to where I was.  I was trying to take it one step at a time, but perhaps I need to get all the links changed at once to point to a website hosted file.  But I don't know why putting the line back the way it was doesn't get rid of the error.
