### ISSUE TITLE
Outlook for Windows stuck to IE11 runtime

### ISSUE THREAD

**Issue by kinkoazc** [OfficeDev/Office-Addin-Scripts#496]
# Expected behavior

Outlook for Windows should use the Edge(es6+) runtime.

# Current behavior

Outlook for Windows uses IE11 runtime, although running `npx office-addin-dev-settings webview manifest.xml edge` returns `The web view type is set to Microsoft Edge (Chromium).`. Even `yo office --projectType single-sign-on --name "My AddIn"  --host outlook --ts true` uses IE11 as runtime, thus failing due to the `es6` compilation target of the `Office-Addin-Scripts` packages.

## Steps to Reproduce

1. Sideload any Outlook Add-In project.
2. Install and open a taskpane.
3. `es6` features of the installed `Office-Addin-Scripts` packages fail at runtime.

## Context

* Beta channel
* Operating System: Windows 10 Pro 21H1 19043.1110, Windows 10 ver. >= 1903
* Node version: 14.17.3
* Office version: Microsoft 365 MSO (16.0.14322.20000) 64-bit, MS 365 Apps for business, Microsoft 365 ver. >= 16.0.13530.20424
* Tool version: yo@4.2.0, generator-office@1.7.9

**Comment by millerds** [comment]
The version of the component used by office depends on more then just the OS, it depends on the version Office.  See the link below for the full explanation.  We've also fixed the project generation so that it compiles for es5 and should work with the IE11 webview (maintaining backward compatibility with different version of Office).

https://support.microsoft.com/en-us/office/which-browsers-work-with-office-for-the-web-and-office-add-ins-ad1303e0-a318-47aa-b409-d3a5eb44e452#:~:text=Office%20Add-ins%20%20%20%20OS%20%20,%20%20Chrome%20%206%20more%20rows%20
