### ISSUE TITLE
Problems sideloading Outlook addin in Outlook 2016

### ISSUE THREAD

**Issue by digitalw** [OfficeDev/Office-Addin-Scripts#809]
Hi, 
I am working onan add-in for Outlook 2016 (big company, migration to never version not yet planed.) I Have 2 Issues

1.) Although the maniferst is valid the addin is not loaded. I get no erroras, warnings or other informaiton. 
I am using Mailbox minVersion 1.4 (Will need Dialog later, but for now this is all)

2.) on my local development machine i have outlook 2019 and the loading of the addin works. However after npm stop, and restart of outlook, the addin is still in the ribbon. And updates of the manifest  (e.G. change of command label ) are not reflected on next start .. needs a coule of tries to get the changes.

Thanks for any support or pointers :-)

**Comment by timwan10** [comment]
For the Outlook 2016 version. What *specific* build are you on? (i.e it should be something like 16.0.XXXX.YYYY). 

If you can put up a copy of the exact manifest that you have, it can help. As there could have been in a bug in Outlook 2016 that was fixed in later versions. (earlier versions of Outlook 2016 also did not support 1.4)   https://learn.microsoft.com/en-us/javascript/api/requirement-sets/outlook/outlook-api-requirement-sets?view=common-js-preview&tabs=xmlmanifest 

Note that those earlier versions of Outlook 2016 are completely out of support now if you are on something like that. You could try downgrading to 1.3 until you need dialog support. 

for #2) Once you remove the add-in from Exchange. it should go away, but it may remain in the local cache for a while. 

You can force the cache to reset by deleting the folder: 

%localappdata%\Microsoft\Office\16.0\Wef

**Comment by digitalw** [comment]
Thanks,
We managed to load it using the web-ui and simply uplodaing the manifest there. Not perfect but works.
I know 2016 is out of support, but our client has no migration plans yet  :-(
