### ISSUE TITLE
getGraphToken is missing

### ISSUE THREAD

**Issue by Edward-Zhou** [OfficeDev/Office-Addin-Scripts#827]
I am referencing [TrainingContent](https://github.com/OfficeDev/TrainingContent/blob/4cfef1166ea4f43f79f8b0393fe17a452cf45e87/OfficeAddin/06%20Using%20Single%20Sign-On%20with%20Office%20Add-ins/Demos/02%20-%20Excel%20Add-in%20SSO/src/helpers/ssoauthhelper.js#L22C54-L22C54) to call graph from excel web addin.

There is code snippet like below:
```
    let bootstrapToken = await OfficeRuntime.auth.getAccessToken({ allowSignInPrompt: true });
    let exchangeResponse = await sso.getGraphToken(bootstrapToken);
    if (exchangeResponse.claims) {
      // Microsoft Graph requires an additional form of authentication. Have the Office host
      // get a new token using the Claims string, which tells AAD to prompt the user for all
      // required forms of authentication.
      let mfaBootstrapToken = await OfficeRuntime.auth.getAccessToken({ authChallenge: exchangeResponse.claims });
      exchangeResponse = sso.getGraphToken(mfaBootstrapToken);
    }
```
But, `getGraphToken` does not exist in latest `office-addin-sso`

**Comment by millerds** [comment]
That training is out of date.  The getGraphToken call was removed almost a year and a half ago because it promoted poor practices for keeping token secured.  It was done in conjunctions with updates to the project generated with 'yo office' that was also updated to encourage more secure token handling.

That specific training content needs to be updated.
