### ISSUE TITLE
WXPO MOS app can't sideload

### ISSUE THREAD

**Issue by hermanwenhe** [OfficeDev/Office-Addin-Scripts#878]
# Expected behavior

Sideload MOS app correctly

# Current behavior

error message: Manifest schema is not valid. Errors: The file assets/color.png could not be found in the app package.
![image](https://github.com/user-attachments/assets/d8bbfbd7-9de3-475d-9965-504d277aa133)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Use yo office to create an outlook add-in with JSON manifest
2. Sideload

## Context

We did some research and found out that it's the `adm-zip`'s behavior change. If we switch the version of `adm-zip` to `0.5.9`, everything would be OK. All versions after `0.5.9` would cause this error.

![image](https://github.com/user-attachments/assets/ef1767e6-f9a5-403a-9be8-59336eb373f1)

**Comment by millerds** [comment]
Note that the package you pointed to is not used to create the zip file that is being sideloaded and throwing the error . . . it's only used to update the WXP file being used to start the host application (with the embedded add-in reference that needs to be updated).  The other package references (specifically office-addin-manifest) are at ^0.5.9, but the '^' allows the install of newer versions (same is true of teamsapp-cli that we are installing).  We could peg all of them to the older version (it's up to 0.5.14 now), but that prevents us from getting any updates and it only a workaround for the real problem.

This problem has existed for several weeks now and the service team is supposed to be make a fix to handle this.  The problem comes from the slashes used in the manifest to reference the color and outline file needing to match the zip file "manifst" (both need to be forward or backward slash).  adm-zip is used to extract and create zip files in various places in our code and we don't control what slash they use (just the version).  We could make a fix here, but we don't control what customers put in their manifest or how they create the zip file so this really needs to be fixed in the service.

**Comment by millerds** [comment]
In looking at the adm-zip repo it looks like they are chasing down compatibility bugs like this.  I will peg the version, but I still thing the service should be able to handle both cases since they are valid zip files (just maybe not cross platform).

**Comment by millerds** [comment]
fixed.  templates need to get updated to require current script versions, but any project can get the current versions if they want.
